FROM %%FROM_IMAGE%%
LABEL org.opencontainers.image.source=https://github.com/sbuerk/test-image-extend
LABEL org.opencontainers.image.description="Extended %%FROM_IMAGE%%"
LABEL org.opencontainers.image.licenses=MIT

# We use convenient install-php-extensions script to manage additional php extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN apk add --no-cache \
        bash \
        file \
        git \
        graphicsmagick \
        grep \
        patch \
        linux-headers \
    && chmod +x /usr/local/bin/install-php-extensions \
    && sync \
    && install-php-extensions \
        ssh2 \
    && apk del linux-headers \
    && rm -rf /var/cache/apk/* /tmp/*