name: image-generator-checker
on:
  schedule:
    - cron: "05 */6 * * *"
  workflow_dispatch:

jobs:
  check:
    name: Check ${{ matrix.docker-image-name }}
    runs-on: ubuntu-latest

    permissions:
      # actions: read|write|none
      actions: none
      # checks: read|write|none
      checks: none
      # contents: read|write|none
      contents: write
      # deployments: read|write|none
      deployments: none
      # id-token: read|write|none
      id-token: none
      # issues: read|write|none
      issues: none
      # discussions: read|write|none
      discussions: none
      # packages: read|write|none
      packages: write
      # pages: read|write|none
      pages: none
      # pull-requests: read|write|none
      pull-requests: none
      # repository-projects: read|write|none
      repository-projects: read
      # security-events: read|write|none
      security-events: none
      # statuses: read|write|none
      statuses: none

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   # This is needed, otherwise the commit push will not trigger the normal on-push workflow
        #   token: ${{ secrets.PACKAGES_GITHUB_TOKEN }}

      - name: Ensure branch is up-to-date
        run: |
          git pull --rebase

      - name: Fetch TYPO3 testing-infrastructure and regenerate core-testing-phpXY templates
        run: |
          ./generate-images.php
          
      - name: Check if repository has changed files
        id: repoStatus
        run: |
          hasChanges=0
          [[ -n $(git status -s) ]] && hasChanges=1
          echo "REPO_IS_DIRTY=$hasChanges" >> $GITHUB_OUTPUT
          
      - name: Create version increase commit
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.repoStatus.outputs.REPO_IS_DIRTY == 1
        with:
          branch: main
          commit_message: "[TASK] TYPO3 PHP core testing image flavours updated"
          commit_options: '--no-verify --signoff'
          commit_user_name: "Image Checker [BOT]"
          commit_user_email: "stefan@buerk.tech"
          commit_author: "Image Checker <stefan@buerk.tech>"
          file_pattern: 'images.json */Dockerfile'
          repository: .